### ISSUE TITLE
signers keys should be added to bitcoin/contrib/gitian-downloader or a new key-list text file

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/gitian.sigs#173]
At the moment it's hard to verify the signatures because not all signers pgp keys are added to https://github.com/bitcoin/bitcoin/tree/master/contrib/gitian-downloader.

Maybe adding each key to this repository would make more sense.

I couldn't fine the pub key for user @centaur.

**Comment by centaur1** [comment]
I saw several that were binary format and several that were text format (e.g. Gavin).  Is there a preferred format?  :-)

**Comment by fanquake** [comment]
Think we can close this now, we've got plenty of keys added to the gitian-downloader directory.

**Comment by laanwj** [comment]
Agreed
